(* ::Package:: *)

(* ::Title::Closed:: *)
(*Setup*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODULE 0: SETUP                                                  *)*)
(*(* ================================================================ *)*)
(**)
(*baseDir = NotebookDirectory[];*)
(*Get[FileNameJoin[{baseDir, "QKT_full.wl"}]];*)
(*$HistoryLength = 0;*)


(* ::Input:: *)
(*EnsureDir[dir_] := If[!DirectoryQ[dir],*)
(*  CreateDirectory[dir, CreateIntermediateDirectories -> True]];*)
(**)
(*kStr[k_] := StringReplace[*)
(*  If[StringEndsQ[#, "."], # <> "0", #] &[ToString[N[k]]], "." -> "_"];*)


(* ::Input:: *)
(*LaunchKernels[14];*)


(* ::Title::Closed:: *)
(*Helpers*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODULE 3: LOCAL HELPERS                                          *)*)
(*(* IntPrCOEFast interpolator + GoF metrics + collage builders      *)*)
(*(* ================================================================ *)*)
(**)
(*Print["\n=== BUILDING HELPERS ==="];*)
(*IntPrCOEFast = Interpolation[*)
(*  Table[{r, NIntegrate[PrCOE[x], {x, 0, r}]}, {r, 0, 1, 0.001}]];*)
(*Print["  IntPrCOEFast[0.5] = ", IntPrCOEFast[0.5]];*)
(**)
(*(* --- GoF metrics from sorted data --- *)*)
(*KSFromSorted[empCDF_List, theoCDFvals_List] := Max[Abs[empCDF - theoCDFvals]];*)
(**)
(*CvMFromSorted[n_Integer, theoCDFvals_List] :=*)
(*  Module[{midEmp = N[(2 Range[n] - 1) / (2 n)]},*)
(*    Total[(midEmp - theoCDFvals)^2] / n + 1 / (12 n)];*)
(**)
(*MSDFromSorted[empCDF_List, theoCDFvals_List] := Mean[(empCDF - theoCDFvals)^2];*)
(**)
(*(* --- GoF for one spectrum (pure numerical, parallelizable) --- *)*)
(*ComputeGoFSingle[specData_Association] :=*)
(*  Module[{spacings, sp, ratios, sortS, sortR, nS, nR,*)
(*          empS, empR, theoS, theoR},*)
(*    spacings = NNSpacings[specData]; sortS = Sort[spacings]; nS = Length[sortS];*)
(*    empS = N[Range[nS] / nS]; theoS = N[IntWignerCOE /@ sortS];*)
(*    sp = Differences[specData["Spectrum"]];*)
(*    ratios = Min /@ Transpose[{Most[sp] / Rest[sp], Rest[sp] / Most[sp]}];*)
(*    sortR = Sort[ratios]; nR = Length[sortR];*)
(*    empR = N[Range[nR] / nR]; theoR = N[IntPrCOEFast /@ sortR];*)
(*    {KSFromSorted[empS, theoS], CvMFromSorted[nS, theoS], MSDFromSorted[empS, theoS],*)
(*     KSFromSorted[empR, theoR], CvMFromSorted[nR, theoR], MSDFromSorted[empR, theoR]}*)
(*  ];*)
(**)
(*(* --- Extract spacings + ratios --- *)*)
(*ExtractStats[specData_Association] :=*)
(*  Module[{spacings, sp, ratios},*)
(*    spacings = NNSpacings[specData];*)
(*    sp = Differences[specData["Spectrum"]];*)
(*    ratios = Min /@ Transpose[{Most[sp] / Rest[sp], Rest[sp] / Most[sp]}];*)
(*    <|"SortedS" -> Sort[spacings], "SortedR" -> Sort[ratios]|>];*)
(**)
(*(* --- Collage row for one sector --- *)*)
(*MakeRowPlots[sortedS_List, sortedR_List, flucData_Association, label_String] :=*)
(*  Module[{nS, nR, empS, empR, theoS, theoR, ksS, ksR, diffS, diffR},*)
(*    nS = Length[sortedS]; nR = Length[sortedR];*)
(*    empS = N[Range[nS] / nS]; empR = N[Range[nR] / nR];*)
(*    theoS = N[IntWignerCOE /@ sortedS];*)
(*    theoR = N[IntPrCOEFast /@ sortedR];*)
(*    ksS = Max[Abs[empS - theoS]]; ksR = Max[Abs[empR - theoR]];*)
(*    diffS = (empS - theoS)^2; diffR = (empR - theoR)^2;*)
(*    {(* P(s) *)*)
(*     Show[Histogram[sortedS, {0, 4, 0.05}, "ProbabilityDensity",*)
(*       ChartStyle -> Directive[LightGray, EdgeForm[Gray]], PlotRange -> {{0, 3.5}, {0, 1.1}}],*)
(*      Plot[WignerCOE[x], {x, 0, 3.5}, PlotStyle -> {Red, Dashed, Thick}],*)
(*      Plot[Exp[-x], {x, 0, 3.5}, PlotStyle -> {Black, Dashed}],*)
(*      $cOpts, FrameLabel -> {"s", "P(s)"}, PlotLabel -> label <> " P(s)", ImageSize -> $cSize],*)
(*     (* P(r) *)*)
(*     Show[Histogram[sortedR, {0, 1, 0.02}, "ProbabilityDensity",*)
(*       ChartStyle -> Directive[LightGray, EdgeForm[Gray]], PlotRange -> {{0, 1}, {0, 2.2}}],*)
(*      Plot[PrCOE[x], {x, 0, 1}, PlotStyle -> {Red, Dashed, Thick}],*)
(*      Plot[PrPoisson[x], {x, 0, 1}, PlotStyle -> {Black, Dashed}],*)
(*      $cOpts, FrameLabel -> {"r", "P(r)"}, PlotLabel -> label <> " P(r)", ImageSize -> $cSize],*)
(*     (* I(s) *)*)
(*     Show[ListLinePlot[Transpose[{sortedS, empS}], PlotStyle -> {Blue, Thick},*)
(*       PlotRange -> {{0, 3.5}, {0, 1}}],*)
(*      Plot[IntWignerCOE[x], {x, 0, 3.5}, PlotStyle -> {Red, Dashed}],*)
(*      Plot[1 - Exp[-x], {x, 0, 3.5}, PlotStyle -> {Black, Dashed}],*)
(*      $cOpts, FrameLabel -> {"s", "I(s)"},*)
(*      PlotLabel -> label <> " I(s) KS=" <> ToString[NumberForm[ksS, 4]], ImageSize -> $cSize],*)
(*     (* I(r) *)*)
(*     Show[ListLinePlot[Transpose[{sortedR, empR}], PlotStyle -> {Blue, Thick},*)
(*       PlotRange -> {{0, 1}, {0, 1}}],*)
(*      ListLinePlot[Transpose[{sortedR, theoR}], PlotStyle -> {Red, Dashed}],*)
(*      $cOpts, FrameLabel -> {"r", "I(r)"},*)
(*      PlotLabel -> label <> " I(r) KS=" <> ToString[NumberForm[ksR, 4]], ImageSize -> $cSize],*)
(*     (* CDF diff (s) *)*)
(*     ListLinePlot[Transpose[{sortedS, diffS}], PlotStyle -> {Blue, Thick},*)
(*      Filling -> Axis, FillingStyle -> Directive[Opacity[0.3], Blue],*)
(*      $cOpts, FrameLabel -> {"s", "(I-I_COE)^2"}, PlotLabel -> label <> " CDF diff (s)",*)
(*      PlotRange -> All, ImageSize -> $cSize],*)
(*     (* CDF diff (r) *)*)
(*     ListLinePlot[Transpose[{sortedR, diffR}], PlotStyle -> {Blue, Thick},*)
(*      Filling -> Axis, FillingStyle -> Directive[Opacity[0.3], Blue],*)
(*      $cOpts, FrameLabel -> {"r", "(I-I_COE)^2"}, PlotLabel -> label <> " CDF diff (r)",*)
(*      PlotRange -> All, ImageSize -> $cSize],*)
(*     (* Fluctuation *)*)
(*     ListLinePlot[Transpose[{flucData["x"], flucData["delta"]}],*)
(*      PlotStyle -> {Blue, AbsoluteThickness[0.5]}, $cOpts,*)
(*      FrameLabel -> {"x", "\!\(\*OverscriptBox[\(N\), \(~\)]\)(x)"},*)
(*      PlotLabel -> label <> " Fluctuation", ImageSize -> $cSize,*)
(*      GridLines -> {None, {0}}, GridLinesStyle -> Directive[Red, Dashed]]}*)
(*  ];*)


(* ::Title::Closed:: *)
(*Parameters*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODULE 1: PARAMETERS                                             *)*)
(*(* ================================================================ *)*)
(**)
(*J       = 500;*)
(*alpha   = 0.84;*)
(*kCenter = 27.5;*)
(*delta   = 0.001;*)
(*nQKT    = 50;*)
(*nCOE    = 50;*)
(*Lmax    = 20;*)
(*lDomain = Join[Range[0.1, 5, 0.1], Range[5.5, Lmax, 0.5]];*)
(*tauMax  = 3.0;*)
(*nPtsSFF = 10000;*)
(**)
(*(* --- Directories --- *)*)
(*runLabel = "J" <> ToString[J] <> "_k" <> kStr[kCenter];*)
(*resultsDir = FileNameJoin[{baseDir, "Results", runLabel}];*)
(*evenDir    = FileNameJoin[{resultsDir, "Even"}];*)
(*oddDir     = FileNameJoin[{resultsDir, "Odd"}];*)
(*plotDir    = FileNameJoin[{resultsDir, "plots"}];*)
(*collageDir = FileNameJoin[{resultsDir, "individual"}];*)
(*EnsureDir[evenDir]; EnsureDir[oddDir];*)
(*EnsureDir[plotDir]; EnsureDir[collageDir];*)
(**)
(*(* --- Plot style --- *)*)
(*$pOpts = Sequence[ImageSize -> 800, Frame -> True,*)
(*  FrameStyle -> Directive[Black, 25],*)
(*  LabelStyle -> Directive[Black, 25]];*)
(*$cOpts = Sequence[Frame -> True,*)
(*  FrameStyle -> Directive[Black, 16],*)
(*  LabelStyle -> Directive[Black, 16]];*)
(*$cSize = 380;*)
(*$legStyle = Directive[Black, 18];*)
(**)
(*SavePlot[plt_, name_] := ( *)
(*  Export[FileNameJoin[{plotDir, name <> ".png"}],*)
(*    Rasterize[plt, ImageResolution -> 150, Background -> White]];*)
(*  Print["  Saved: ", name, ".png"]);*)


(* ::Title:: *)
(*Method*)


(* ::Input:: *)
(*  (* --- Generate --- *)*)
(*  Print["=== GENERATING QKT ENSEMBLE ==="];*)
(*(*  SeedRandom[42];*)*)
(*  kList = RandomReal[{kCenter - delta, kCenter + delta}, nQKT];*)
(*  {tGen, qktEnsemble} = AbsoluteTiming[*)
(*    GenerateQKTEnsemble[J, alpha, kList]];*)
(*  Print["  ", nQKT, " matrices done in ", Round[tGen, 0.1], "s"];*)
(*  Export[FileNameJoin[{evenDir, "spectra_k"<>ToString[kCenter]<>".wdx"}], qktEnsemble["Even"], "WDX"];*)
(*  Export[FileNameJoin[{oddDir, "spectra_k"<>ToString[kCenter]<>".wdx"}], qktEnsemble["Odd"], "WDX"];*)
(*  Print["  Spectra exported"];*)


(* ::Input:: *)
(*(* --- Import --- *)*)
(*(*qktEnsemble = <|*)
(*    "Even" -> Import[FileNameJoin[{evenDir, "spectra.wdx"}]],*)
(*    "Odd"  -> Import[FileNameJoin[{oddDir, "spectra.wdx"}]]|>;*)
(*  If[FailureQ[qktEnsemble["Even"]] || FailureQ[qktEnsemble["Odd"]],*)
(*    Print["ERROR: Import failed. Check paths."]; Abort[]];*)
(*  Print["  Imported successfully"];*)*)
(*  qktEnsemble = <|*)
(*    "Even" -> Import["C:\\Users\\Miguel\\Github\\Chaotic_eigenfunctions\\Spectral measures analysis\\Results\\J500_k27_5\\Even\\spectra_k27.5.wdx"],*)
(*    "Odd"  -> Import["C:\\Users\\Miguel\\Github\\Chaotic_eigenfunctions\\Spectral measures analysis\\Results\\J500_k27_5\\Odd\\spectra_k27.5.wdx"]|>;*)
(**)
(*  If[FailureQ[qktEnsemble["Even"]] || FailureQ[qktEnsemble["Odd"]],*)
(*    Print["ERROR: Import failed. Check paths."]; Abort[]];*)
(*  Print["  Imported successfully"];*)


(* ::Input:: *)
(*dimE = qktEnsemble["Even"][[1]]["N"];*)
(*dimO = qktEnsemble["Odd"][[1]]["N"];*)
(*nReal = Length[qktEnsemble["Even"]];*)
(*Print["  Even N=", dimE, ", Odd N=", dimO, ", nReal=", nReal];*)


(* ::Title::Closed:: *)
(*Individual realization*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODULE 4: INDIVIDUAL REALIZATION COLLAGES                        *)*)
(*(* ================================================================ *)*)
(**)
(*Print["\n=== INDIVIDUAL COLLAGES ==="];*)
(**)
(*Do[*)
(*  Module[{stE, stO, flE, flO, colE, colO, collage},*)
(*    stE = ExtractStats[qktEnsemble["Even"][[i]]];*)
(*    stO = ExtractStats[qktEnsemble["Odd"][[i]]];*)
(*    flE = GetFluctuations[qktEnsemble["Even"][[i]]];*)
(*    flO = GetFluctuations[qktEnsemble["Odd"][[i]]];*)
(*    colE = MakeRowPlots[stE["SortedS"], stE["SortedR"], flE, "Even"];*)
(*    colO = MakeRowPlots[stO["SortedS"], stO["SortedR"], flO, "Odd"];*)
(*    collage = Grid[*)
(*      Prepend[Transpose[{colE, colO}],*)
(*        {Style["Even", Bold, 20], Style["Odd", Bold, 20]}],*)
(*      Spacings -> {1, 0.5}, Frame -> All, FrameStyle -> GrayLevel[0.85]];*)
(*    Export[FileNameJoin[{collageDir,*)
(*      "realization_" <> StringPadLeft[ToString[i], 4, "0"] <> ".png"}],*)
(*      Rasterize[collage, ImageResolution -> 150, Background -> White]];*)
(*    If[Mod[i, 50] == 0 || i == 1, Print["  Exported ", i, "/", nReal]];*)
(*  ];*)
(*, {i, nReal}];*)
(*Print["Individual collages complete"];*)


(* ::Title::Closed:: *)
(*Coe reference*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODULE 6: COE REFERENCE + NUMBER VARIANCE + SFF                  *)*)
(*(* ================================================================ *)*)
(**)
(*Print["\n=== COE REFERENCE ==="];*)
(*dimCOE = dimE;*)
(*{tCOE, coeSpectra} = AbsoluteTiming[GenerateCOEEnsemble[dimCOE, nCOE]];*)
(*Print["  ", nCOE, " COE(", dimCOE, ") done in ", Round[tCOE, 0.1], "s"];*)
(**)
(*Print["Computing COE Sigma2..."];*)
(*{tS, sigma2COE} = AbsoluteTiming[EnsembleSigma2[coeSpectra, lDomain]];*)
(*Print["  Done in ", Round[tS, 0.1], "s"];*)
(**)
(*Print["Computing COE SFF..."];*)
(*{tF, sffCOE} = AbsoluteTiming[EnsembleSFF[coeSpectra, tauMax, nPtsSFF]];*)
(*Print["  Done in ", Round[tF, 0.1], "s"];*)
(*coeSpectra = .;*)
(**)
(*Print["\n=== QKT NUMBER VARIANCE ==="];*)
(*{t1, sigma2Even} = AbsoluteTiming[EnsembleSigma2[qktEnsemble["Even"], lDomain]];*)
(*{t2, sigma2Odd}  = AbsoluteTiming[EnsembleSigma2[qktEnsemble["Odd"], lDomain]];*)
(*Print["  Even: ", Round[t1, 0.1], "s, Odd: ", Round[t2, 0.1], "s"];*)
(**)
(*SavePlot[Legended[Show[*)
(*  ListLinePlot[Transpose[{sigma2COE["LValues"], sigma2COE["Sigma2TheorMean"]}], PlotStyle -> {Red, Thick}],*)
(*  ListLinePlot[Transpose[{sigma2Even["LValues"], sigma2Even["Sigma2TheorMean"]}], PlotStyle -> {Blue, Thick}],*)
(*  ListLinePlot[Transpose[{sigma2Odd["LValues"], sigma2Odd["Sigma2TheorMean"]}], PlotStyle -> {Darker[Green], Thick}],*)
(*  Plot[COEAsymptoticSigma2[L], {L, 0.5, Lmax}, PlotStyle -> {Orange, Thick, Dashed}],*)
(*  Plot[L, {L, 0.5, Lmax}, PlotStyle -> {Black, Dashed, Thin}],*)
(*  $pOpts, FrameLabel -> {"L", "\!\(\*SuperscriptBox[\(\[Sigma]\), \(2\)]\)(L)"},*)
(*  PlotLabel -> "Number Variance: J=" <> ToString[J],*)
(*  PlotRange -> {All, {0, Automatic}}],*)
(*  Placed[LineLegend[{Directive[Blue, Thick], Directive[Darker[Green], Thick],*)
(*    Directive[Red, Thick], Directive[Orange, Thick, Dashed]},*)
(*    {"Even", "Odd", "COE", "COE asym."}, LabelStyle -> $legStyle], {Right, Bottom}]*)
(*], "sigma2"];*)
(**)
(*(* Residual *)*)
(*Module[{nMin, lR, resE, resO},*)
(*  nMin = Min[Length /@ {sigma2Even["LValues"], sigma2Odd["LValues"], sigma2COE["LValues"]}];*)
(*  lR = sigma2COE["LValues"][[1 ;; nMin]];*)
(*  resE = sigma2Even["Sigma2TheorMean"][[1 ;; nMin]] - sigma2COE["Sigma2TheorMean"][[1 ;; nMin]];*)
(*  resO = sigma2Odd["Sigma2TheorMean"][[1 ;; nMin]] - sigma2COE["Sigma2TheorMean"][[1 ;; nMin]];*)
(*  SavePlot[Legended[Show[*)
(*    ListLinePlot[Transpose[{lR, resE}], PlotStyle -> {Blue, Thick}],*)
(*    ListLinePlot[Transpose[{lR, resO}], PlotStyle -> {Darker[Green], Thick}],*)
(*    Plot[0, {x, 0, Max[lR]}, PlotStyle -> {Red, Dashed}],*)
(*    $pOpts, FrameLabel -> {"L", "\[CapitalDelta]\!\(\*SuperscriptBox[\(\[Sigma]\), \(2\)]\)(L)"},*)
(*    PlotLabel -> "Residual: QKT - COE"],*)
(*    Placed[LineLegend[{Directive[Blue, Thick], Directive[Darker[Green], Thick]},*)
(*      {"Even", "Odd"}, LabelStyle -> $legStyle], {Right, Bottom}]*)
(*  ], "residual"];*)
(*];*)
(**)
(*Export[FileNameJoin[{evenDir, "sigma2.wdx"}], sigma2Even, "WDX"];*)
(*Export[FileNameJoin[{oddDir, "sigma2.wdx"}], sigma2Odd, "WDX"];*)
(**)
(*Print["\n=== SFF ==="];*)
(*{t1, sffEven} = AbsoluteTiming[EnsembleSFF[qktEnsemble["Even"], tauMax, nPtsSFF]];*)
(*{t2, sffOdd}  = AbsoluteTiming[EnsembleSFF[qktEnsemble["Odd"], tauMax, nPtsSFF]];*)
(*Print["  Even: ", Round[t1, 0.1], "s, Odd: ", Round[t2, 0.1], "s"];*)
(**)
(*SavePlot[Legended[Show[*)
(*  ListLinePlot[GaussianFilter[Transpose[{sffCOE["Tau"], sffCOE["MeanK"]}],5], PlotStyle -> {Red, Thick}],*)
(*  ListLinePlot[GaussianFilter[Transpose[{sffEven["Tau"], sffEven["MeanK"]}],5], PlotStyle -> {Blue, Thick}],*)
(*  ListLinePlot[GaussianFilter[Transpose[{sffOdd["Tau"], sffOdd["MeanK"]}],5], PlotStyle -> {Darker[Green], Thick}],*)
(*  Plot[COESFFAnalytical[tau], {tau, 0.001, tauMax}, PlotStyle -> {Black, Thick, Dashed}],*)
(*  $pOpts, FrameLabel -> {"\[Tau]", "K(\[Tau])"},*)
(*  PlotLabel -> "SFF: J=" <> ToString[J], PlotRange -> {{0, tauMax}, {0, 1.5}}],*)
(*  Placed[LineLegend[{Directive[Blue, Thick], Directive[Darker[Green], Thick],*)
(*    Directive[Red, Thick], Directive[Black, Thick, Dashed]},*)
(*    {"Even", "Odd", "COE", "COE analyt."}, LabelStyle -> $legStyle], {Right, Bottom}]*)
(*], "sff"];*)


(* ::Input:: *)
(*SavePlot[Legended[Show[*)
(*  ListLinePlot[GaussianFilter[Transpose[{sffCOE["Tau"], sffCOE["MeanK"]}],5], PlotStyle -> {Red, Thick}],*)
(*  ListLinePlot[GaussianFilter[Transpose[{sffEven["Tau"], sffEven["MeanK"]}],5], PlotStyle -> {Blue, Thick}],*)
(*  ListLinePlot[GaussianFilter[Transpose[{sffOdd["Tau"], sffOdd["MeanK"]}],5], PlotStyle -> {Darker[Green], Thick}],*)
(*  Plot[COESFFAnalytical[tau], {tau, 0.001, tauMax}, PlotStyle -> {Black, Thick, Dashed}],*)
(*  $pOpts, FrameLabel -> {"\[Tau]", "K(\[Tau])"},*)
(*  PlotLabel -> "SFF: J=" <> ToString[J], PlotRange -> {{0, tauMax}, {0, 1.5}}],*)
(*  Placed[LineLegend[{Directive[Blue, Thick], Directive[Darker[Green], Thick],*)
(*    Directive[Red, Thick], Directive[Black, Thick, Dashed]},*)
(*    {"Even", "Odd", "COE", "COE analyt."}, LabelStyle -> $legStyle], {Right, Bottom}]*)
(*], "sff"]*)


(* ::Title:: *)
(*Pooled ensemble*)


(* ::Input:: *)
(*(* ================================================================*)(*MODULE 4.5:GLOBAL ENSEMBLE STATISTICS (POOLED)*)(* ================================================================*)*)
(*Print["\n=== GLOBAL ENSEMBLE STATISTICS ==="];*)
(**)
(*(*---1. Unfold Locally and Pool Globally---*)*)
(*Print["Pooling data..."];*)
(**)
(*(*Extract local lists for Even sector and flatten into global lists*)*)
(*localStatsEven=ParallelMap[ExtractStats,qktEnsemble["Even"]];*)
(*globalSEven=Sort[Flatten[localStatsEven[[All,"SortedS"]]]];*)
(*globalREven=Sort[Flatten[localStatsEven[[All,"SortedR"]]]];*)
(**)
(*(*Extract local lists for Odd sector and flatten into global lists*)*)
(*localStatsOdd=ParallelMap[ExtractStats,qktEnsemble["Odd"]];*)
(*globalSOdd=Sort[Flatten[localStatsOdd[[All,"SortedS"]]]];*)
(*globalROdd=Sort[Flatten[localStatsOdd[[All,"SortedR"]]]];*)
(**)
(*Print["Pooled Even: ",Length[globalSEven]," levels. Pooled Odd: ",Length[globalSOdd]," levels."];*)
(**)
(*(*---2. Compute Global GoF Metrics---*)*)
(*Print["Computing global errors..."];*)
(**)
(*computeGlobalGoF[sortedS_,sortedR_]:=Module[{nS,nR,empS,empR,theoS,theoR},nS=Length[sortedS];*)
(*nR=Length[sortedR];*)
(*empS=N[Range[nS]/nS];*)
(*empR=N[Range[nR]/nR];*)
(*theoS=N[IntWignerCOE/@sortedS];*)
(*theoR=N[IntPrCOEFast/@sortedR];*)
(*<|"KS_s"->KSFromSorted[empS,theoS],"CvM_s"->CvMFromSorted[nS,theoS],"MSD_s"->MSDFromSorted[empS,theoS],"KS_r"->KSFromSorted[empR,theoR],"CvM_r"->CvMFromSorted[nR,theoR],"MSD_r"->MSDFromSorted[empR,theoR]|>];*)
(**)
(*globalGoFEven=computeGlobalGoF[globalSEven,globalREven];*)
(*globalGoFOdd=computeGlobalGoF[globalSOdd,globalROdd];*)
(**)
(*Print["Even Global GoF: "];*)
(*Print[globalGoFEven];*)
(*Print["Odd Global GoF: "];*)
(*Print[globalGoFOdd];*)
(**)
(*(*---3. Generate and Save the Global Collages---*)*)
(*Print["Generating global plots..."];*)
(**)
(*(*Note:We pass an empty association <||> for flucData if MakeRowPlots requires 4 arguments*)*)
(*globalPlotsEven=MakeRowPlots[globalSEven,globalREven,<||>,"Even (Global)"];*)
(*globalPlotsOdd=MakeRowPlots[globalSOdd,globalROdd,<||>,"Odd (Global)"];*)
(**)
(*globalCollageEven=GraphicsGrid[Partition[globalPlotsEven,2],ImageSize->1200,Spacings->{40,40}];*)
(**)
(*globalCollageOdd=GraphicsGrid[Partition[globalPlotsOdd,2],ImageSize->1200,Spacings->{40,40}];*)
(**)
(*SavePlot[globalCollageEven,"global_collage_even"];*)
(*SavePlot[globalCollageOdd,"global_collage_odd"];*)
(**)
(*Print["Global ensemble analysis complete!"];*)


(* ::Title::Closed:: *)
(*Length spectrum*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODULE 7: FLUCTUATION + LENGTH SPECTRUM                          *)*)
(*(* ================================================================ *)*)
(**)
(*Print["\n=== FLUCTUATION ANALYSIS ==="];*)
(*flucEven = GetFluctuations[qktEnsemble["Even"][[1]]];*)
(*flucOdd  = GetFluctuations[qktEnsemble["Odd"][[1]]];*)
(**)
(*SavePlot[Legended[Show[*)
(*  ListLinePlot[Transpose[{flucEven["x"], flucEven["delta"]}], PlotStyle -> {Blue, AbsoluteThickness[0.5]}],*)
(*  ListLinePlot[Transpose[{flucOdd["x"], flucOdd["delta"]}], PlotStyle -> {Darker[Green], AbsoluteThickness[0.5]}],*)
(*  $pOpts, FrameLabel -> {"x", "\!\(\*OverscriptBox[\(N\), \(~\)]\)(x)"},*)
(*  PlotLabel -> "Fluctuating Staircase",*)
(*  GridLines -> {None, {0}}, GridLinesStyle -> Directive[Red, Dashed]],*)
(*  Placed[LineLegend[{Directive[Blue], Directive[Darker[Green]]},*)
(*    {"Even", "Odd"}, LabelStyle -> $legStyle], {Right, Bottom}]*)
(*], "fluctuations"];*)
(**)
(*lsEven = LengthSpectrum[flucEven]; lsOdd = LengthSpectrum[flucOdd];*)
(*SavePlot[Legended[Show[*)
(*  ListLinePlot[Transpose[{lsEven["Period"][[1 ;; 50]], lsEven["Amplitude"][[1 ;; 50]]}],*)
(*    PlotStyle -> {Blue, AbsoluteThickness[1.5]}],*)
(*  ListLinePlot[Transpose[{lsOdd["Period"][[1 ;; 50]], lsOdd["Amplitude"][[1 ;; 50]]}],*)
(*    PlotStyle -> {Red, AbsoluteThickness[1.5]}],*)
(*  $pOpts, FrameLabel -> {"Period (kicks)", "Length Spectrum"}, PlotLabel -> "Length Spectrum",*)
(*  GridLines -> {None, {0}}, GridLinesStyle -> Directive[Gray, Dashed]],*)
(*  Placed[LineLegend[{Directive[Blue], Directive[Red]},*)
(*    {"Even", "Odd"}, LabelStyle -> $legStyle], {Right, Bottom}]*)
(*], "length_spectrum"];*)


(* ::Chapter:: *)
(*Peaks average*)


(* ::Input:: *)
(*(*Ensemble-averaged length spectrum power*)*)
(*allPower=Table[FluctuationPowerSpectrum[GetFluctuations[qktEnsemble["Odd"][[i]]]]["Power"],{i,nReal}];*)
(*meanPower=Mean[allPower];*)
(*freqs=FluctuationPowerSpectrum[GetFluctuations[qktEnsemble["Odd"][[1]]]]["Freq"];*)
(**)
(*ListLinePlot[Transpose[{freqs,meanPower}],PlotRange->All,$pOpts,FrameLabel->{"Frequency","<|delta_k|^2>"},PlotLabel->"Ensemble-averaged power spectrum"]*)


(* ::Title::Closed:: *)
(*Gof*)


(* ::Input:: *)
(*(* ================================================================ *)*)
(*(* MODULE 9: GoF ERRORS (parallelized per realization)              *)*)
(*(* ================================================================ *)*)
(**)
(*Print["\n=== GoF PER REALIZATION ==="];*)
(*DistributeDefinitions[ComputeGoFSingle, NNSpacings, IntWignerCOE, IntPrCOEFast,*)
(*  KSFromSorted, CvMFromSorted, MSDFromSorted];*)
(**)
(*{tE, gofEvenAll} = AbsoluteTiming[*)
(*  ParallelTable[ComputeGoFSingle[qktEnsemble["Even"][[i]]],*)
(*    {i, nReal}, Method -> "CoarsestGrained"]];*)
(*{tO, gofOddAll} = AbsoluteTiming[*)
(*  ParallelTable[ComputeGoFSingle[qktEnsemble["Odd"][[i]]],*)
(*    {i, nReal}, Method -> "CoarsestGrained"]];*)
(*Print["  Even: ", Round[tE, 0.1], "s, Odd: ", Round[tO, 0.1], "s"];*)
(**)
(*labels = {"KS_s", "CvM_s", "MSD_s", "KS_r", "CvM_r", "MSD_r"};*)
(*Do[*)
(*  Print["  ", labels[[idx]], ": Even mean=",*)
(*    NumberForm[Mean[gofEvenAll[[All, idx]]], 4],*)
(*    ", Odd mean=", NumberForm[Mean[gofOddAll[[All, idx]]], 4]];*)
(*, {idx, 6}];*)
(**)
(*(* Histograms *)*)
(*Do[*)
(*  Module[{eV = gofEvenAll[[All, idx]], oV = gofOddAll[[All, idx]]},*)
(*    SavePlot[Legended[Show[*)
(*      Histogram[{eV, oV}, Automatic, "ProbabilityDensity",*)
(*        ChartStyle -> {Directive[Blue, Opacity[0.5]], Directive[Darker[Green], Opacity[0.5]]}],*)
(*      $pOpts, FrameLabel -> {labels[[idx]], "Density"},*)
(*      PlotLabel -> labels[[idx]] <> " distribution (" <> ToString[nReal] <> " realizations)"],*)
(*      Placed[LineLegend[{Directive[Blue, Opacity[0.5]], Directive[Darker[Green], Opacity[0.5]]},*)
(*        {"Even", "Odd"}, LabelStyle -> $legStyle], {Right, Top}]*)
(*    ], "gof_" <> labels[[idx]]]];*)
(*, {idx, 6}];*)
(**)
(*Export[FileNameJoin[{evenDir, "gof.wdx"}], gofEvenAll, "WDX"];*)
(*Export[FileNameJoin[{oddDir, "gof.wdx"}], gofOddAll, "WDX"];*)


(* ::Title:: *)
(*SFF*)


(* ::Input:: *)
(*EnsembleSFFFull[spectraList_List,tauMax_Real,nPts_Integer]:=Module[{nMat,taus,specArray,allK},nMat=Length[spectraList];*)
(*taus=N[Range[1,nPts] (tauMax/nPts)];*)
(*specArray=Map[#["Spectrum"]&,spectraList];*)
(*DistributeDefinitions[CompileSFF,taus,specArray];*)
(*allK=ParallelTable[CompileSFF[specArray[[i]],taus],{i,nMat},Method->"CoarsestGrained"];*)
(*<|"Tau"->taus,"AllK"->allK,"MeanK"->Mean[allK],"SE"->StandardDeviation[allK]/Sqrt[nMat*1.]|>];*)
(*SmoothSFF[kVec_List,tauVec_List,sigmaTau_?NumericQ]:=GaussianFilter[kVec,sigmaTau/(tauVec[[2]]-tauVec[[1]])];*)


(* ::Chapter:: *)
(*method*)


(* ::Input:: *)
(*tauMaxSFF=3.0;*)
(*nPtsSFF=10000;*)
(*sigmaSm=0.01;*)
(**)
(*sffEven=EnsembleSFFFull[qktEnsemble["Even"],tauMaxSFF,nPtsSFF];*)
(*sffOdd=EnsembleSFFFull[qktEnsemble["Odd"],tauMaxSFF,nPtsSFF];*)
(*sffCOE=EnsembleSFFFull[coeSpectra,tauMaxSFF,nPtsSFF];*)
(**)
(*tauGrid=sffEven["Tau"];*)
(**)
(*(*Smooth each realization individually,then take the mean of the smoothed curves*)*)
(*kEvenAllSm=Map[SmoothSFF[#,tauGrid,sigmaSm]&,sffEven["AllK"]];*)
(*kOddAllSm=Map[SmoothSFF[#,tauGrid,sigmaSm]&,sffOdd["AllK"]];*)
(*kCOEAllSm=Map[SmoothSFF[#,tauGrid,sigmaSm]&,sffCOE["AllK"]];*)
(**)
(*kEvenMeanSm=Mean[kEvenAllSm];*)
(*kOddMeanSm=Mean[kOddAllSm];*)
(*kCOEMeanSm=Mean[kCOEAllSm];*)
(**)
(*kCOEAn=Map[COESFFAnalytical,tauGrid];*)


(* ::Chapter:: *)
(*plotting*)


(* ::Input:: *)
(*(*Pick one representative realization for the "individual" panel*)*)
(*iShow=10;*)
(**)
(*plotIndiv=ListLinePlot[{Transpose[{tauGrid,sffEven["AllK"][[iShow]]}],Transpose[{tauGrid,kEvenAllSm[[iShow]]}],Transpose[{tauGrid,kCOEAn}]},PlotStyle->{Directive[Thin,Gray],Directive[Thick,RGBColor[0.2,0.4,0.8]],Directive[Thick,Dashed,Red]},PlotLegends->{"raw K_i","smoothed K_i","COE analytical"},Frame->True,FrameLabel->{"\[Tau]","K(\[Tau])"},PlotLabel->"Single realization (Even sector, i="<>ToString[iShow]<>")",ImageSize->700]*)


(* ::Input:: *)
(*plotEnsemble=ListLinePlot[{Transpose[{tauGrid,kEvenMeanSm}],Transpose[{tauGrid,kOddMeanSm}],Transpose[{tauGrid,kCOEAn}]},PlotStyle->{Directive[Thick,RGBColor[0.2,0.4,0.8]],Directive[Thick,RGBColor[0.8,0.3,0.2]],Directive[Thick,RGBColor[0.3,0.6,0.3]],Directive[Thick,Dashed,Red]},PlotLegends->{"Even smoothed mean","Odd smoothed mean","COE","COE analytical"},Frame->True,FrameLabel->{"\[Tau]","K(\[Tau])"},PlotLabel->"Ensemble SFF, M = 50, J = 500",ImageSize->700,LabelStyle->Directive[Black,20]]*)


(* ::Input:: *)
(*plot=ListLogLogPlot[{Transpose[{tauGrid,kEvenMeanSm}],Transpose[{tauGrid,kOddMeanSm}],Transpose[{tauGrid,kCOEAn}]},PlotStyle->{Directive[Thick,RGBColor[0.2,0.4,0.8]],Directive[Thick,RGBColor[0.8,0.3,0.2]],Directive[Thick,RGBColor[0.3,0.6,0.3]],Directive[Thick,Dashed,Red]},PlotLegends->{"Even smoothed mean","Odd smoothed mean","COE","COE analytical"},Frame->True,FrameLabel->{"\[Tau]","K(\[Tau])"},PlotLabel->"Ensemble SFF, M = 50, J = 500",ImageSize->700,LabelStyle->Directive[Black,20]]*)
